apiVersion: v1
kind: Secret
metadata: {name: {{ .Release.Name }}-secrets}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  POLICY_SIGNING_KEY: {{ .Values.secrets.POLICY_SIGNING_KEY | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
